server:
  port: 8080
config:
  info: test-config-info
spring:
  application:
    name: lcc
  cloud:
    nacos:
      discovery:
        server-addr: 10.120.22.66:8848
      config:
        server-addr: 10.120.22.66:8848
        file-extension: yaml